/**
 * DSH 契约快照与差异分析（**纯逻辑**：不联网、不碰文件系统）。
 *
 * ## 这个模块回答什么问题
 *
 * 「官方这次更新，会不会让本扩展的某段代码失效？」——答案只取决于两件事：
 * 官方**契约面**变了什么，以及本扩展**消费面**是什么。前者从官方发布产物里抽，
 * 后者从本仓库已有的唯一登记点取（投影键、事件表、端点调用点），两者求交即影响面。
 *
 * ## 为什么能离线做
 *
 * 官方每个 api 包都随包发布 `lib/typert.host.js`（typert 生成器产物，文件头逐字写着
 * `Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit.`），
 * 里面是 `TYPERT` 描述符：每个 invocation 的 `namespace`/`method`、每个参数的**线上字段名**
 * （`wire`）、以及 `codec.typeSymbol` 指向的契约类型。`lib/**\/*.d.ts` 则有完整的类型面。
 * 两者都能从 `npm pack` 的 tarball 里直接读到——**不需要装、不需要起 `dsh web`、不花 token**。
 *
 * 历史上咬过本扩展的两类破坏都在这个面上可见：
 * `commands/execute` 第三参数 `images` → `submittedAttachments`（参数 `wire` 改名），
 * `session/follow` 的 `assistantStream` 是字面量 `true`（类型面字面量变化）。
 *
 * ## 判定分级
 *
 * - **P0 破坏**：本扩展**在用**的东西消失 / 改名 / 形状变 —— 不改代码就会坏。
 * - **P1 新增**：官方新增了端点 / 事件 / 类型 —— 不崩，是否跟进是产品决策。
 * - **P2 无关**：不在消费面上的变化 —— 只需记录「已核对」。
 *
 * 官方自己用的是同一套做法：`docs/persistence-changes/releases/dsh-v*.schema.json` 逐 tag
 * 存契约快照，配 `scripts/persistence-releases.ts` 比对。
 */

// ---------------------------------------------------------------- 版本与渠道

/**
 * 官方只发四档（`scripts/release/families.ts` 的 `DshFamily.distTagForVersion`）：
 * 无预发布段 → npm `latest`；`rc.N` → `next`；`alpha.N` → `alpha`；`canary.N` → `canary`。
 * **没有 beta 档**——`beta` 在这里单列只是为了不把未知渠道误判成 rc。
 */
export type DshChannel = "stable" | "rc" | "alpha" | "canary" | "beta" | "other";

export interface DshVersion {
  readonly major: number;
  readonly minor: number;
  readonly patch: number;
  readonly channel: DshChannel;
  readonly prerelease: string | undefined;
}

const VERSION_PATTERN = /^(\d+)\.(\d+)\.(\d+)(?:-([0-9A-Za-z.-]+))?$/;

/** 解析官方版本串；不是合法 semver 时给 `undefined`（调用点据此报错，不猜）。 */
export function parseDshVersion(version: string): DshVersion | undefined {
  const match = VERSION_PATTERN.exec(version.trim());
  if (match === null) return undefined;
  const prerelease = match[4];
  return {
    major: Number(match[1]),
    minor: Number(match[2]),
    patch: Number(match[3]),
    prerelease,
    channel: channelOf(prerelease),
  };
}

function channelOf(prerelease: string | undefined): DshChannel {
  if (prerelease === undefined) return "stable";
  const head = prerelease.split(".")[0];
  if (head === "rc" || head === "alpha" || head === "canary" || head === "beta") return head;
  return "other";
}

/** semver 优先级比较：先比数字段，预发布版低于同号正式版，再逐字段比预发布标识。 */
export function compareDshVersions(left: string, right: string): number {
  const a = parseDshVersion(left);
  const b = parseDshVersion(right);
  if (a === undefined || b === undefined) return left.localeCompare(right);
  const numbers = a.major - b.major || a.minor - b.minor || a.patch - b.patch;
  if (numbers !== 0) return numbers;
  if (a.prerelease === undefined || b.prerelease === undefined) {
    if (a.prerelease === b.prerelease) return 0;
    return a.prerelease === undefined ? 1 : -1;
  }
  const leftFields = a.prerelease.split(".");
  const rightFields = b.prerelease.split(".");
  for (let index = 0; index < Math.max(leftFields.length, rightFields.length); index += 1) {
    const one = leftFields[index];
    const other = rightFields[index];
    if (one === undefined) return -1;
    if (other === undefined) return 1;
    const oneNumber = /^\d+$/.test(one) ? Number(one) : undefined;
    const otherNumber = /^\d+$/.test(other) ? Number(other) : undefined;
    if (oneNumber !== undefined && otherNumber !== undefined) {
      if (oneNumber !== otherNumber) return oneNumber - otherNumber;
      continue;
    }
    if (oneNumber !== undefined) return -1;
    if (otherNumber !== undefined) return 1;
    if (one !== other) return one.localeCompare(other);
  }
  return 0;
}

/** 版本串是否已进入官方 git tag 命名空间（`dsh-v0.1.5-rc.3` → `0.1.5-rc.3`）。 */
export function versionFromTag(tag: string): string | undefined {
  const match = /^dsh-v(\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?)$/.exec(tag.trim());
  return match?.[1];
}

// ---------------------------------------------------------------- 契约快照

/** 一个端点的线上形状：谁做 scope、要发哪些 `wire` 字段、涉及哪些契约类型。 */
export interface EndpointContract {
  /** invocation 的 scope 字段名（`kind: 'context'` 时它也是必发参数），无 scope 为 `null`。 */
  readonly scope: string | null;
  /** `parameters` 里逐个参数的线上字段名，保持描述符里的顺序。 */
  readonly params: readonly string[];
  /** 该端点 `codec.typeSymbol` 引用的契约类型（`<包>#<类型名>` 或 `<包>#<端点>:<角色>`）。 */
  readonly types: readonly string[];
}

export interface PackageContract {
  readonly endpoints: Record<string, EndpointContract>;
  /** 该包对外发的 scoped 事件名（描述符里 `mode: "emit"` 的那些）。 */
  readonly events: readonly string[];
  /** 导出的类型名 → 归一化后的成员/右值文本数组。 */
  readonly types: Record<string, readonly string[]>;
}

export interface ContractSnapshot {
  readonly formatVersion: typeof SNAPSHOT_FORMAT_VERSION;
  readonly version: string;
  readonly generatedAt: string;
  readonly packages: Record<string, PackageContract>;
  /** 该版本上没取到的包（下架 / 改名 / 网络失败）——**必须显式记录**，缺证据不等于没影响。 */
  readonly missing: readonly string[];
}

/**
 * 快照格式版本。抽取规则变了就把它加一：旧的快照文件与新的抽取结果不可比，
 * 与其拿两套规则的结果做差（会凭空多出一堆「变化」），不如重抓。
 */
export const SNAPSHOT_FORMAT_VERSION = 2;

const EMPTY_PACKAGE: PackageContract = { endpoints: {}, events: [], types: {} };

/** 从 `lib/typert.host.js` 抽出端点与事件。 */
export function extractTypertContract(source: string): { endpoints: Record<string, EndpointContract>; events: readonly string[] } {
  const endpoints: Record<string, EndpointContract> = {};
  for (const chunk of invocationChunks(source)) {
    const id = /namespace:\s*'([^']+)'[\s\S]*?method:\s*'([^']+)'/.exec(chunk);
    if (id === null) continue;
    const scopeMatch = /scope:\s*\{\s*context:\s*'[^']*'\s*,\s*wire:\s*'([^']+)'/.exec(chunk);
    endpoints[`${id[1]}/${id[2]}`] = {
      scope: scopeMatch === null ? null : scopeMatch[1],
      params: parameterWires(chunk),
      types: [...new Set([...chunk.matchAll(/typeSymbol:\s*'([^']+)'/g)].map((match) => match[1]))],
    };
  }
  return { endpoints, events: [...new Set([...source.matchAll(/"name":\s*"([^"]+)",\s*\n\s*"mode":\s*"emit"/g)].map((match) => match[1]))].sort() };
}

/** 切出 `invocations: [` 数组里逐个 invocation 对象的正文（每个对象以 4 空格缩进开头）。 */
function invocationChunks(source: string): string[] {
  const start = source.indexOf("invocations: [");
  if (start === -1) return [];
  const end = source.indexOf("\n  ],", start);
  const body = source.slice(start, end === -1 ? source.length : end);
  return body.split(/\n {4}\{\n/).slice(1);
}

/** 取参数数组里每个参数的 `wire`（scope 的 `wire` 不在这个数组里，故不混进来）。 */
function parameterWires(chunk: string): string[] {
  const start = chunk.indexOf("parameters: [");
  if (start === -1) return [];
  const end = chunk.indexOf("\n      ],", start);
  const body = chunk.slice(start, end === -1 ? chunk.length : end);
  return [...body.matchAll(/\n {10}wire:\s*'([^']+)'/g)].map((match) => match[1]);
}

/**
 * 从一组 `.d.ts` 抽类型面：导出的 `interface` 与 `type` 别名，值归一化成单行文本数组
 * （保留嵌套结构的整体形状，所以「内层字段改名」也能看出来）。
 *
 * 抽取前**先去掉注释**：官方习惯顺手改 JSDoc，注释进了成员文本就会把「只改了文档」报成
 * 形状变化——一份总在喊「破坏性变更」的报告等于没有报告（实测 0.1.5-rc.3 → 0.1.6-alpha.1
 * 的三个 P0 里有两个是这么来的）。
 */
export function extractTypeContract(files: readonly { path: string; text: string }[]): Record<string, readonly string[]> {
  const types: Record<string, string[]> = {};
  for (const file of files) {
    for (const declaration of declarationsOf(stripComments(file.text))) {
      if (!(declaration.name in types)) types[declaration.name] = declaration.members;
    }
  }
  return types;
}

function stripComments(text: string): string {
  return text.replace(/\/\*[\s\S]*?\*\//g, "").replace(/(^|\s)\/\/[^\n]*/g, "$1");
}

interface Declaration {
  readonly name: string;
  readonly members: string[];
}

function declarationsOf(text: string): Declaration[] {
  const out: Declaration[] = [];
  const pattern = /export (?:declare )?(interface|type) ([A-Za-z0-9_$]+)[^{;]*/g;
  for (const match of text.matchAll(pattern)) {
    const kind = match[1];
    const name = match[2];
    const start = (match.index ?? 0) + match[0].length;
    const members = kind === "interface" ? membersOfBlock(text, start) : [statementText(text, start)];
    if (members.length > 0) out.push({ name, members });
  }
  return out;
}

/** 读 `{ ... }` 里的成员：按花括号深度切，成员文本连同其嵌套结构一起归一化。 */
function membersOfBlock(text: string, start: number): string[] {
  const open = text.indexOf("{", start);
  if (open === -1) return [];
  const members: string[] = [];
  let depth = 1;
  let buffer: string[] = [];
  for (const raw of text.slice(open + 1).split("\n")) {
    const line = raw.trim();
    const closed = line === "}" && depth === 1;
    if (closed) break;
    if (depth === 1 && line === "") continue;
    depth += countOf(line, "{", "}");
    if (line !== "") buffer.push(line);
    if (depth === 1 && buffer.length > 0) {
      members.push(buffer.join(" ").replace(/\s+/g, " ").trim());
      buffer = [];
    }
  }
  return members;
}

/** 读 `type X = ...;` 的右值直到深度归零的分号。 */
function statementText(text: string, start: number): string {
  const buffer: string[] = [];
  let depth = 0;
  for (const raw of text.slice(start).split("\n")) {
    const line = raw.trim();
    if (line === "") continue;
    buffer.push(line);
    depth += countOf(line, "{", "}") + countOf(line, "(", ")") + countOf(line, "[", "]");
    if (depth <= 0 && line.endsWith(";")) break;
  }
  return buffer.join(" ").replace(/\s+/g, " ").trim();
}

function countOf(line: string, open: string, close: string): number {
  let delta = 0;
  for (const character of line) {
    if (character === open) delta += 1;
    else if (character === close) delta -= 1;
  }
  return delta;
}

// ---------------------------------------------------------------- 消费面与差异

/** 本扩展实际用到的东西。三个集合都从仓库里已有的唯一登记点推出来，不另立清单。 */
export interface ConsumptionSurface {
  /** 调用过的端点（`namespace/method`）。 */
  readonly endpoints: ReadonlySet<string>;
  /** 消费过的事件类型名。 */
  readonly events: ReadonlySet<string>;
  /** 源码里引用过的契约类型名。 */
  readonly types: ReadonlySet<string>;
}

export type ChangeLevel = "P0" | "P1" | "P2";

export interface ContractChange {
  readonly level: ChangeLevel;
  readonly package: string;
  readonly kind: string;
  readonly name: string;
  readonly detail: string;
}

/** 两个快照求差，并按消费面分级。`from` 是上一已核对版本，`to` 是待核对版本。 */
export function diffSnapshots(from: ContractSnapshot, to: ContractSnapshot, consumed: ConsumptionSurface): ContractChange[] {
  const changes: ContractChange[] = [];
  const packages = [...new Set([...Object.keys(from.packages), ...Object.keys(to.packages)])].sort();
  for (const name of packages) {
    const before = from.packages[name] ?? EMPTY_PACKAGE;
    const after = to.packages[name];
    if (after === undefined) {
      const used = Object.keys(before.endpoints).some((endpoint) => consumed.endpoints.has(endpoint));
      changes.push({ level: used ? "P0" : "P2", package: name, kind: "package-removed", name, detail: "该版本未发布这个包" });
      continue;
    }
    diffEndpoints(name, before, after, consumed, changes);
    diffEvents(name, before, after, consumed, changes);
    diffTypes(name, before, after, consumed, changes);
  }
  return changes.sort((left, right) => left.level.localeCompare(right.level) || left.package.localeCompare(right.package) || left.kind.localeCompare(right.kind) || left.name.localeCompare(right.name));
}

function diffEndpoints(pkg: string, before: PackageContract, after: PackageContract, consumed: ConsumptionSurface, changes: ContractChange[]): void {
  for (const [endpoint, contract] of Object.entries(before.endpoints)) {
    const used = consumed.endpoints.has(endpoint);
    const next = after.endpoints[endpoint];
    if (next === undefined) {
      changes.push({ level: used ? "P0" : "P2", package: pkg, kind: "endpoint-removed", name: endpoint, detail: "端点消失" });
      continue;
    }
    if (contract.params.join(",") !== next.params.join(",")) {
      changes.push({
        level: used ? "P0" : "P2",
        package: pkg,
        kind: "endpoint-params",
        name: endpoint,
        detail: `参数 ${describeList(contract.params)} → ${describeList(next.params)}`,
      });
    }
    if (contract.scope !== next.scope) {
      changes.push({
        level: used ? "P0" : "P2",
        package: pkg,
        kind: "endpoint-scope",
        name: endpoint,
        detail: `scope ${describeList(contract.scope === null ? [] : [contract.scope])} → ${describeList(next.scope === null ? [] : [next.scope])}`,
      });
    }
  }
  for (const endpoint of Object.keys(after.endpoints)) {
    if (!(endpoint in before.endpoints)) {
      changes.push({ level: "P1", package: pkg, kind: "endpoint-added", name: endpoint, detail: `参数 ${describeList(after.endpoints[endpoint]?.params ?? [])}` });
    }
  }
}

function diffEvents(pkg: string, before: PackageContract, after: PackageContract, consumed: ConsumptionSurface, changes: ContractChange[]): void {
  const beforeEvents = new Set(before.events);
  const afterEvents = new Set(after.events);
  for (const event of beforeEvents) {
    if (!afterEvents.has(event)) {
      const used = consumed.events.has(event);
      changes.push({ level: used ? "P0" : "P2", package: pkg, kind: "event-removed", name: event, detail: "事件不再发出" });
    }
  }
  for (const event of afterEvents) {
    if (!beforeEvents.has(event)) changes.push({ level: "P1", package: pkg, kind: "event-added", name: event, detail: "新增事件" });
  }
}

function diffTypes(pkg: string, before: PackageContract, after: PackageContract, consumed: ConsumptionSurface, changes: ContractChange[]): void {
  for (const [name, members] of Object.entries(before.types)) {
    const used = consumed.types.has(name);
    const next = after.types[name];
    if (next === undefined) {
      changes.push({ level: used ? "P0" : "P2", package: pkg, kind: "type-removed", name, detail: "类型消失" });
      continue;
    }
    const delta = memberDelta(members, next);
    // 只有顺序变了：接口的成员顺序不参与语义，不报（否则报告全是噪声）
    if (!delta.changed) continue;
    // **只新增不是破坏**：读的一方不受影响（只有「成员消失 / 成员内容变了」才可能让我们读错）。
    // 我们消费的类型只新增时给 P1——若那恰好是我们**构造**的请求类型，需人工确认新字段是否必填。
    changes.push({
      level: used ? (delta.additive ? "P1" : "P0") : "P2",
      package: pkg,
      kind: delta.additive ? "type-members-added" : "type-members",
      name,
      detail: delta.detail,
    });
  }
  for (const name of Object.keys(after.types)) {
    if (!(name in before.types)) changes.push({ level: "P1", package: pkg, kind: "type-added", name, detail: "新增类型" });
  }
}

interface MemberDelta {
  readonly removed: readonly string[];
  readonly added: readonly string[];
  /** 变化是否**只是新增**（读的一方不受影响）。嵌套结构里多一个字段也算只新增。 */
  readonly additive: boolean;
  /** 是否真的有变化（只调了成员顺序时为 false）。 */
  readonly changed: boolean;
  /** 已渲染好的差异说明。 */
  readonly detail: string;
}

/**
 * 成员级差异。
 *
 * 「删掉一个成员」与「成员内部多了一个字段」在集合差异里长得一样（都是旧行消失 + 新行出现），
 * 但一个是破坏、一个不是。所以对一对一的增删再切一次公共前后缀：**去掉公共前后缀后只剩新增
 * 内容的，就是只新增**（`SessionEventMap` 的 `'tool/result'` 在 0.1.6-alpha.1 里加了
 * `reason?: string;`，曾被报成 P0）。
 */
function memberDelta(before: readonly string[], after: readonly string[]): MemberDelta {
  const beforeSet = new Set(before);
  const afterSet = new Set(after);
  const removed = before.filter((member) => !afterSet.has(member));
  const added = after.filter((member) => !beforeSet.has(member));
  if (removed.length === 0 && added.length === 0) return { removed, added, additive: true, changed: false, detail: "" };

  if (removed.length === 1 && added.length === 1) {
    const pair = trimPair(removed[0], added[0]);
    const removedBare = bare(pair.removedMiddle);
    const addedBare = bare(pair.addedMiddle);
    // 只新增：旧的一侧没有实质内容，或者它的内容整个出现在新的一侧里
    const additive = removedBare === "" || addedBare.includes(removedBare);
    const onlyRemoved = addedBare === "" || removedBare.includes(addedBare);
    if (removedBare === "" && addedBare === "") return { removed: [], added: [], additive: true, changed: false, detail: "" };
    if (additive) return { removed, added, additive: true, changed: true, detail: `+ …${clip(pair.addedMiddle)}` };
    if (onlyRemoved) return { removed, added, additive: false, changed: true, detail: `− …${clip(pair.removedMiddle)}` };
    return {
      removed,
      added,
      additive: false,
      changed: true,
      detail: `− …${clip(pair.removedMiddle)}；+ …${clip(pair.addedMiddle)}`,
    };
  }

  const parts: string[] = [];
  if (removed.length > 0) parts.push(`− ${removed.map((member) => clip(member)).join(", ")}`);
  if (added.length > 0) parts.push(`+ ${added.map((member) => clip(member)).join(", ")}`);
  return { removed, added, additive: removed.length === 0, changed: true, detail: parts.join("；") };
}

interface MemberPair {
  readonly removedMiddle: string;
  readonly addedMiddle: string;
}

function trimPair(before: string, after: string): MemberPair {
  const shared = commonPrefixLength(before, after);
  let suffix = 0;
  const limit = Math.min(before.length, after.length) - shared;
  while (suffix < limit && before[before.length - 1 - suffix] === after[after.length - 1 - suffix]) suffix += 1;
  return {
    removedMiddle: before.slice(shared, before.length - suffix),
    addedMiddle: after.slice(shared, after.length - suffix),
  };
}

/** 去掉标点与空白，只留「实义内容」——用于判断一侧是不是另一侧的扩展。 */
function bare(text: string): string {
  return text.replace(/[\s;,{}()[\]]/g, "");
}

function commonPrefixLength(left: string, right: string): number {
  const limit = Math.min(left.length, right.length);
  let index = 0;
  while (index < limit && left[index] === right[index]) index += 1;
  return index;
}

function clip(text: string): string {
  return text.length <= 120 ? text : `${text.slice(0, 117)}…`;
}

/** 端点参数 / scope 的前后对照，报告里用。 */
function describeList(items: readonly string[]): string {
  return items.length === 0 ? "（无）" : `[${items.join(", ")}]`;
}

/** 报告正文。按级别分组，P0 在前。 */
export function renderReport(from: string, to: string, changes: readonly ContractChange[]): string {
  const lines = [`# DSH 契约差异 ${from} → ${to}`, ""];
  for (const level of ["P0", "P1", "P2"] as const) {
    const bucket = changes.filter((change) => change.level === level);
    lines.push(`## ${level}（${bucket.length}）`, "");
    if (bucket.length === 0) {
      lines.push("无", "");
      continue;
    }
    for (const change of bucket) {
      lines.push(`- \`${change.package}\` **${change.kind}** \`${change.name}\` — ${change.detail}`);
    }
    lines.push("");
  }
  return lines.join("\n");
}

/** 给核对结论用的一句话摘要。 */
export function summarize(changes: readonly ContractChange[]): string {
  const count = (level: ChangeLevel) => changes.filter((change) => change.level === level).length;
  const p0 = count("P0");
  if (p0 > 0) return `需兼容更新（P0 ${p0} / P1 ${count("P1")} / P2 ${count("P2")}）`;
  return `无影响（P1 ${count("P1")} / P2 ${count("P2")}）`;
}
